### ISSUE TITLE
losing state on page refresh

### ISSUE THREAD

**Issue by RoyalTS** [MarkEdmondson1234/googleID#3]
When running the example app, refreshing the browser window loses the logged in state and asks me to log in again.

With the [bookmarkable state](http://shiny.rstudio.com/articles/bookmarking-state.html) feature in shiny 0.14 a `state` GET parameter is appended to the URL after log in. A page refresh now no longer completely loses state but the app still throws

> Error: JSON fetch error: Invalid Credentials

Is there any way to restore state completely after page refresh?

**Comment by MarkEdmondson1234** [comment]
This may be possible, but will also need to check that this isn't a security risk, as in a bookmarkable URL that anyone can login with your details.  I think the tokens last 60 mins though so shouldn't be too bad.  

At present, if using the older R based authentication, a new "state" parameter is made for every load of the Shiny app via `getOption("googleAuthR.securitycode")` - I think if you set this instead to a static value then the same authentication will work.  You can try this out by setting it at the top of a Shiny script (after googleAuthR has loaded)

I'm not sure how the JavaScript based auth handles it.

**Comment by berksarioz** [comment]
I also would like to stay logged in at page refresh, so I'd appreciate updates.

**Comment by angelobj** [comment]
I would also like to be logged at page refresh

**Comment by MarkEdmondson1234** [comment]
Use the new googleSignIn() Shiny module in googleAuthR v0.7.0. 

GoogleID library will be retired as it’s using Google+ API that doesn’t work anymore.

**Comment by angelobj** [comment]
It works awesome Awesome! Thanks for all the hard work
